export const Languages = {
    en : {
        "Sign_In" : "Sign In",
        "Username_or_email" : "Username",
        "Enter_email_your_account" : "Enter email your account.",
        "Password": "Password",
        "Enter_password_length_is_8_character" : "Enter password length is 8 character.",
        "Forgot_password_" : "Forgot password ?",
        "Dont_have_an_account" : "Don’t have an account?",
        "Sign_up" : "Sign up",
        "Full_name" : "Full name",
        "Enter_your_full_name" : "Enter your full name.",
        "Already_have_account" : "Already have account?",
        "Forgot_password" : "Forgot password",
        "About_developer" : "About developer",
        "Click_here" : "Click here",
        "Send_verification" : "Send verification",
        "username_must_email_and_password_min_length_is_8" : "username must email, and password min length is 8.",
        "Please_fill_all_required_field" : "Please fill all required field.",
        "Success_register_user" : "Success register user.",
        "Email_sended" : "Email success sended.",
        "username_must_email" : "username must email.",
        "Transaction_report" : "Transaction report",
        "today" : "Today",
        "yesterday" : "Yesterday",
        "filter_date" : "Filter Date",
        "download_report" : "Download Report",
        "transaction" : "Transaction",
        "income" : "Income",
        "hey_today_not_any_transaction" : "Hey, today not any transaction, create your frist transaction.",
        "store" : "Store",
        "Enter_store" : "Enter store if you owner.",
        "customer" : "Customer",
        "Enter_customer" : "Enter customer name.",
        "total_weight" : "Total weight",
        "enter_weight" : "Enter weight laundry.",
        "save_transaction" : "Save transaction",
        "close" : "Close",
        "offline" : "You are offline now, check your connection.",
        "saved_data" : "Success, data saved.",
        "success_deleted" : "Success, deleted transaction",
        "confirm_delete_trans" : "Are you sure to delete Trasaction ?",
        "store_report" : "Store report",
        "total_all_store" : "Total all store",
        "settings" : "Settings",
        "logout" : "Logout",
        "change_password" : "Change password",
        "new_password" : "New password",
        "enter_new_password" : "Enter your new password.",
        "confirm_password" : "Confirm password",
        "enter_confirm_password" : "Enter again your new password.",
        "save" : "Save",
        "change_lang" : "Change language",
        "not_match_password" : "New password not match.",
        "success_change_pass" : "Success change password."
    },
    id : {
        "Sign_In" : "Masuk",
        "Username_or_email" : "Nama penguna",
        "Enter_email_your_account" : "Masukkan email akun Anda.",
        "Password": "Kata sandi",
        "Enter_password_length_is_8_character" : "Masukkan panjang sandi 8 karakter.",
        "Forgot_password_" : "Lupa kata sandi ?",
        "Dont_have_an_account" : "Tidak punya akun?",
        "Sign_up" : "Daftar",
        "Full_name" : "Nama lengkap",
        "Enter_your_full_name" : "Masukan nama lengkap anda.",
        "Already_have_account" : "Sudah punya akun?",
        "Forgot_password" : "Lupa kata sandi",
        "About_developer" : "Tentang pengembang",
        "Click_here" : "Klik disini",
        "Send_verification" : "Kirim verifikasi",
        "username_must_email_and_password_min_length_is_8" : "nama penguna harus email, dan panjang minimal kata sandi adalah 8.",
        "Please_fill_all_required_field" : "Silakan isi semua bagian yang wajib diisi.",
        "Success_register_user" : "Registrasi penguna sukses.",
        "Email_sended" : "Email berhasil dikirim.",
        "username_must_email" : "nama penguna harus email.",
        "Transaction_report" : "Laporan transaksi",
        "today" : "Hari ini",
        "yesterday" : "Kemarin",
        "filter_date" : "Pilah berdasarkan tanggal",
        "download_report" : "Unduh laporan",
        "transaction" : "Transaksi",
        "income" : "Pendapatan",
        "hey_today_not_any_transaction" : "Hey, hari ini tidak ada transaksi, buat transaksi anda.",
        "store" : "Toko",
        "Enter_store" : "Masukan toko jika anda pemilik.",
        "customer" : "Pelangan",
        "Enter_customer" : "Masukan nama pelangan.",
        "total_weight" : "Total berat",
        "enter_weight" : "Masukan total berat laundry.",
        "save_transaction" : "Simpan transaksi",
        "close" : "Tutup",
        "offline" : "Koneksi internet kamu sedang tergangu, cek koneksi kamu.",
        "saved_data" : "Sukses, data tersimpan.",
        "success_deleted" : "Sukses, transaksi di hapus.",
        "confirm_delete_trans" : "Apakah yakin ingin menghapus transaksi ?",
        "store_report" : "Laporan toko",
        "total_all_store" : "Total semua toko",
        "settings" : "Pengaturan",
        "logout" : "Keluar",
        "change_password" : "Ganti kata sandi",
        "new_password" : "Kata sandi baru",
        "enter_new_password" : "Masukan kata sandi barumu.",
        "confirm_password" : "Konfirmasi katas andi",
        "enter_confirm_password" : "Masukan lagi kata sandi barumu.",
        "save" : "Simpan",
        "change_lang" : "Ganti bahasa",
        "not_match_password" : "Password tidak sama.",
        "success_change_pass" : "Sukses password di ganti."
    }
}